
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('songs').del()
    .then(function () {
      // Inserts seed entries
      return knex('songs').insert([
        {id: 1, setlist_id: 1, title: 'From the Prison'},
        {id: 2, setlist_id: 1, title: 'Lets Get Together'},
        {id: 3, setlist_id: 1, title: 'The Minstrel from Gault'},
        {id: 4, setlist_id: 1, title: 'Im a Stranger Here'},
        {id: 5, setlist_id: 1, title: 'High Flying Bird'},
        {id: 6, setlist_id: 1, title: 'I Cant Make It Anymore'},
        {id: 7, setlist_id: 1, title: 'With A Little Help From My Friends'},
        {id: 8, setlist_id: 1, title: 'Handsome Johnny'},
        {id: 9, setlist_id: 1, title: 'Strawberry Fields Forever / Hey Jude'},
        {id: 10, setlist_id: 1, title: 'Freedom/Motherless Child'},
        {id: 11, setlist_id: 2, title: 'Coming into Los Angeles'},
        {id: 12, setlist_id: 2, title: 'Wheel of Fortune'},
        {id: 13, setlist_id: 2, title: 'Walkin Down the Line'},
        {id: 14, setlist_id: 2, title: 'Story about Moses and the Brownies'},
        {id: 15, setlist_id: 2, title: 'Mary Dont You Weep'},
        {id: 16, setlist_id: 2, title: 'Every Hand in the Land'},
        {id: 17, setlist_id: 2, title: 'Amazing Grace'},
        {id: 18, setlist_id: 3, title: 'Oh Happy Day'},
        {id: 19, setlist_id: 3, title: 'The Last Thing on My Mind'},
        {id: 20, setlist_id: 3, title: 'I Shall Be Released'},
        {id: 21, setlist_id: 3, title: 'Story about how the Federal Marshals came to take David Harris into custody'},
        {id: 22, setlist_id: 3, title: 'No Expectations'},
        {id: 23, setlist_id: 3, title: 'Joe Hill'},
        {id: 24, setlist_id: 3, title: 'Sweet Sir Galahad'},
        {id: 25, setlist_id: 3, title: 'Hickory Wind'},
        {id: 26, setlist_id: 3, title: 'Drug Store Truck Driving Man'},
        {id: 27, setlist_id: 3, title: 'I Live One Day at a Time'},
        {id: 28, setlist_id: 3, title: 'Take Me Back to the Sweet Sunny South'},
        {id: 29, setlist_id: 3, title: 'Let Me Wrap You In My Warm and Tender Love'},
        {id: 30, setlist_id: 3, title: 'Swing Low, Sweet Chariot'},
        {id: 31, setlist_id: 3, title: 'We Shall Overcome'},
        {id: 32, setlist_id: 4, title: 'Waiting'},
        {id: 33, setlist_id: 4, title: 'Evil Ways'},
        {id: 34, setlist_id: 4, title: 'You Just Dont Care'},
        {id: 35, setlist_id: 4, title: 'Savor'},
        {id: 36, setlist_id: 4, title: 'Jingo'},
        {id: 37, setlist_id: 4, title: 'Persuasion'},
        {id: 38, setlist_id: 4, title: 'Soul Sacrifice'},
        {id: 39, setlist_id: 4, title: 'Fried Neckbones and Some Home Fries'},
        {id: 40, setlist_id: 5, title: 'St. Stephen'},
        {id: 41, setlist_id: 5, title: 'Mama Tried'},
        {id: 42, setlist_id: 5, title: 'Dark Star'},
        {id: 43, setlist_id: 5, title: 'High Time'},
        {id: 44, setlist_id: 5, title: 'Turn on Your Love Light'},
        {id: 45, setlist_id: 6, title: 'Born on the Bayou'},
        {id: 46, setlist_id: 6, title: 'Green River'},
        {id: 47, setlist_id: 6, title: 'Ninety-Nine and a Half (Wont Do)'},
        {id: 48, setlist_id: 6, title: 'Commotion'},
        {id: 49, setlist_id: 6, title: 'Bootleg'},
        {id: 50, setlist_id: 6, title: 'Bad Moon Rising'},
        {id: 51, setlist_id: 6, title: 'Proud Mary'},
        {id: 52, setlist_id: 6, title: 'I Put a Spell on You'},
        {id: 53, setlist_id: 6, title: 'Night Time Is the Right Time'},
        {id: 54, setlist_id: 6, title: 'Keep on Chooglin'},
        {id: 55, setlist_id: 6, title: 'Susie Q'},
        {id: 56, setlist_id: 7, title: 'Raise Your Hand'},
        {id: 57, setlist_id: 7, title: 'As Good As Youve Been to This World'},
        {id: 58, setlist_id: 7, title: 'To Love Somebody'},
        {id: 59, setlist_id: 7, title: 'Summertime'},
        {id: 60, setlist_id: 7, title: 'Try (Just a Little Bit Harder)'},
        {id: 61, setlist_id: 7, title: 'Kozmic Blues'},
        {id: 62, setlist_id: 7, title: 'Cant Turn You Loose'},
        {id: 63, setlist_id: 7, title: 'Work Me, Lord'},
        {id: 64, setlist_id: 7, title: 'Piece of My Heart'},
        {id: 65, setlist_id: 7, title: 'Ball n Chain'},
        {id: 66, setlist_id: 8, title: 'Heaven and Hell'},
        {id: 67, setlist_id: 8, title: 'I Cant Explain'},
        {id: 68, setlist_id: 8, title: 'Its a Boy'},
        {id: 69, setlist_id: 8, title: '1921'},
        {id: 70, setlist_id: 8, title: 'Amazing Journey'},
        {id: 71, setlist_id: 8, title: 'Sparks'},
        {id: 72, setlist_id: 8, title: 'Eyesight to the Blind'},
        {id: 73, setlist_id: 8, title: 'Christmas'},
        {id: 74, setlist_id: 8, title: 'Acid Queen'},
        {id: 75, setlist_id: 8, title: 'Pinball Wizard'},
        {id: 76, setlist_id: 8, title: 'Do You Think Its Alright?'},
        {id: 77, setlist_id: 8, title: 'Fiddle About'},
        {id: 78, setlist_id: 8, title: 'Theres a Doctor'},
        {id: 79, setlist_id: 8, title: 'Go to the Mirror'},
        {id: 80, setlist_id: 8, title: 'Smash the Mirror'},
        {id: 81, setlist_id: 8, title: 'Im Free'},
        {id: 82, setlist_id: 8, title: 'Tommys Holiday Camp'},
        {id: 83, setlist_id: 8, title: 'Were Not Gonna Take It'},
        {id: 84, setlist_id: 8, title: 'See Me, Feel Me'},
        {id: 85, setlist_id: 8, title: 'Summertime Blues'},
        {id: 86, setlist_id: 8, title: 'Shakin All Over'},
        {id: 87, setlist_id: 8, title: 'My Generation'},
        {id: 88, setlist_id: 8, title: 'Naked Eye'},
        {id: 89, setlist_id: 8, title: 'Heaven and Hell'},
        {id: 90, setlist_id: 9, title: 'The Other Side of This Life'},
        {id: 91, setlist_id: 9, title: 'Somebody to Love'},
        {id: 92, setlist_id: 9, title: '3/5 of a Mile in 10 Seconds'},
        {id: 93, setlist_id: 9, title: 'Wont You Try/Saturday Afternoon'},
        {id: 94, setlist_id: 9, title: 'Eskimo Blue Day'},
        {id: 95, setlist_id: 9, title: 'Plastic Fantastic Lover'},
        {id: 96, setlist_id: 9, title: 'Wooden Ships'},
        {id: 97, setlist_id: 9, title: 'Uncle Sam Blues'},
        {id: 98, setlist_id: 9, title: 'Volunteers'},
        {id: 99, setlist_id: 9, title: 'The Ballad of You and Me and Pooneil'},
        {id: 100, setlist_id: 9, title: 'Come Back Baby'},
        {id: 101, setlist_id: 9, title: 'White Rabbit'},
        {id: 102, setlist_id: 9, title: 'The House at Pooneil Corners'},
        {id: 101, setlist_id: 10, title: 'Dear Landlord'},
        {id: 102, setlist_id: 10, title: 'Something Comin On'},
        {id: 103, setlist_id: 10, title: 'Do I Still Figure in Your Life'},
        {id: 104, setlist_id: 10, title: 'Feelin Alright'},
        {id: 105, setlist_id: 10, title: 'Just Like a Woman'},
        {id: 106, setlist_id: 10, title: 'Lets Go Get Stoned'},
        {id: 107, setlist_id: 10, title: 'I Dont Need a Doctor'},
        {id: 108, setlist_id: 10, title: 'I Shall Be Released'},
        {id: 109, setlist_id: 10, title: 'Hitchcock Railway'},
        {id: 110, setlist_id: 10, title: 'Something to Say'},
        {id: 111, setlist_id: 10, title: 'With a Little Help from My Friends'},
        {id: 112, setlist_id: 11, title: 'Suite: Judy Blue Eyes'},
        {id: 113, setlist_id: 11, title: 'Blackbird'},
        {id: 114, setlist_id: 11, title: 'Helplessly Hoping'},
        {id: 115, setlist_id: 11, title: 'Guinnevere'},
        {id: 116, setlist_id: 11, title: 'Marrakesh Express'},
        {id: 117, setlist_id: 11, title: '4 + 20'},
        {id: 118, setlist_id: 11, title: 'Mr. Soul'},
        {id: 119, setlist_id: 11, title: 'Wonderin'},
        {id: 120, setlist_id: 11, title: 'You Dont Have to Cry'},
        {id: 121, setlist_id: 11, title: '49 Bye-Byes'},
        {id: 122, setlist_id: 12, title: 'Get a Job'},
        {id: 123, setlist_id: 12, title: 'Come Go with Me'},
        {id: 124, setlist_id: 12, title: 'Silhouettes'},
        {id: 125, setlist_id: 12, title: 'Teen Angel'},
        {id: 126, setlist_id: 12, title: 'Jailhouse Rock'},
        {id: 127, setlist_id: 12, title: 'Wipe Out'},
        {id: 128, setlist_id: 12, title: 'Blue Moon'},
        {id: 129, setlist_id: 12, title: '(Who Wrote) The Book of Love'},
        {id: 130, setlist_id: 12, title: 'Little Darlin'},
        {id: 131, setlist_id: 12, title: 'At the Hop'},
        {id: 132, setlist_id: 12, title: 'Duke of Earl'},
        {id: 133, setlist_id: 12, title: 'Get a Job (Reprise)'},
        {id: 134, setlist_id: 13, title: 'Message to Love'},
        {id: 135, setlist_id: 13, title: 'Hear My Train A Comin'},
        {id: 136, setlist_id: 13, title: 'Spanish Castle Magic'},
        {id: 137, setlist_id: 13, title: 'Red House'},
        {id: 138, setlist_id: 13, title: 'Mastermind'},
        {id: 139, setlist_id: 13, title: 'Lover Man'},
        {id: 140, setlist_id: 13, title: 'Foxy Lady'},
        {id: 141, setlist_id: 13, title: 'Jam Back at the House'},
        {id: 142, setlist_id: 13, title: 'Izabella'},
        {id: 143, setlist_id: 13, title: 'Gypsy Woman/Aware of Love'},
        {id: 144, setlist_id: 13, title: 'Fire'},
        {id: 145, setlist_id: 13, title: 'Voodoo Child (Slight Return)/Stepping Stone'},
        {id: 146, setlist_id: 13, title: 'The Star-Spangled Banner'},
        {id: 147, setlist_id: 13, title: 'Purple Haze'},
        {id: 148, setlist_id: 13, title: 'Villanova Junction'},
        {id: 149, setlist_id: 13, title: 'Hey Joe'},

      ]);
    });
};
